<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <groupId>sh.trishul</groupId>
    <artifactId>trishul-ai-service</artifactId>
    <description>AI Service Implementation (LangChain4j integration)</description>
    <packaging>jar</packaging>

    <parent>
        <groupId>sh.trishul</groupId>
        <artifactId>trishul-parent</artifactId>
        <version>1.0.0</version>
        <relativePath>../../pom.xml</relativePath>
    </parent>

    <properties>
    </properties>

    <dependencies>
        <dependency>
            <groupId>sh.trishul</groupId>
            <artifactId>trishul-test-bom</artifactId>
        </dependency>

        <dependency>
            <groupId>sh.trishul</groupId>
            <artifactId>trishul-ai</artifactId>
        </dependency>

        <dependency>
            <groupId>sh.trishul</groupId>
            <artifactId>trishul-tenant</artifactId>
        </dependency>

        <dependency>
            <groupId>sh.trishul</groupId>
            <artifactId>trishul-tenant-service</artifactId>
        </dependency>

        <dependency>
            <groupId>sh.trishul</groupId>
            <artifactId>trishul-crud</artifactId>
        </dependency>

        <!-- Spring AI / Langchain dependencies -->
        <dependency>
            <groupId>dev.langchain4j</groupId>
            <artifactId>langchain4j-spring-boot-starter</artifactId>
            <version>${dev.langchain4j.spring-boot.version}</version>
        </dependency>
        <dependency>
            <groupId>dev.langchain4j</groupId>
            <artifactId>langchain4j-open-ai-spring-boot-starter</artifactId>
            <version>${dev.langchain4j.spring-boot.version}</version>
        </dependency>
        <dependency>
            <groupId>dev.langchain4j</groupId>
            <artifactId>langchain4j-anthropic-spring-boot-starter</artifactId>
            <version>${dev.langchain4j.spring-boot.version}</version>
            <exclusions>
                <exclusion>
                    <groupId>dev.langchain4j</groupId>
                    <artifactId>langchain4j-http-client-jdk</artifactId>
                </exclusion>
            </exclusions>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-websocket</artifactId>
        </dependency>
    </dependencies>

</project>
