version: "3.3"
services:
  install:
    image: maven:3.6.3-openjdk-17
    container_name: maven_install
    working_dir: ${PWD}
    command: ['mvn', 'clean', 'install']
    environment:
      ENABLE_TESTS: "${ENABLE_TESTS}"
      ENABLE_CODE_COVERAGE: "${ENABLE_CODE_COVERAGE}"
      ENABLE_MUTATION_COVERAGE: "${ENABLE_MUTATION_COVERAGE}"
      ENABLE_CHECKSTYLE: "${ENABLE_CHECKSTYLE}"
      ENABLE_VERSION_BUMP: "${ENABLE_VERSION_BUMP}"
      ENABLE_SONARQUBE: "${ENABLE_SONARQUBE}"
      ENABLE_DEPENDENCY_CHECK: "${ENABLE_DEPENDENCY_CHECK}"
      ENABLE_SPOTBUGS: "${ENABLE_SPOTBUGS}"
      SPOTBUGS_FAIL_ON_ERROR: "${SPOTBUGS_FAIL_ON_ERROR}"
      ENABLE_FORMATTING: "${ENABLE_FORMATTING}"
      APP_URL: "${APP_URL}"
      SONARQUBE_HOST_URL: "${SONARQUBE_HOST_URL}"
      SONARQUBE_LOGIN: "${SONARQUBE_LOGIN}"
      SONARQUBE_PROJECT_KEY: "${SONARQUBE_PROJECT_KEY}"
      NVD_API_KEY: "${NVD_API_KEY}"
      ENABLE_OPENAPI_SPEC_GENERATION: "${ENABLE_OPENAPI_SPEC_GENERATION}"
    volumes:
      - ${PWD}:${PWD}
      - ${HOME}/.m2/:/root/.m2

  compile:
    image: maven:3.6.3-openjdk-17
    container_name: maven_compile
    working_dir: ${PWD}
    command: ['mvn', 'compile', '-T', '1C', '-q']
    environment:
      ENABLE_CHECKSTYLE: "${ENABLE_CHECKSTYLE}"
      ENABLE_FORMATTING: "${ENABLE_FORMATTING}"
    volumes:
      - ${PWD}:${PWD}
      - ${HOME}/.m2/:/root/.m2
