CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE CURRENCY (
    NUMERIC_CODE INTEGER PRIMARY KEY,
    CODE CHAR(3) NOT NULL
);
INSERT INTO CURRENCY VALUES (124, 'CAD');

CREATE TABLE QTY_UNIT (
    SYMBOL VARCHAR(4) PRIMARY KEY,
    NAME VARCHAR(255) UNIQUE NOT NULL,
    BASE_UNIT_SYMBOL VARCHAR(4) REFERENCES QTY_UNIT(SYMBOL)
);

--Predefined Quantity Units
INSERT INTO QTY_UNIT VALUES
    ('mg', 'Milligram', 'kg'),
    ('g', 'Gram', 'kg'),
    ('kg', 'Kilogram', 'kg'),
    ('ml', 'Millilitre', 'l'),
    ('l', 'Litre', 'l'),
    ('hl', 'Hectolitre', 'l'),
    ('each', 'Each', 'each');

CREATE TABLE USER_STATUS (
    ID INTEGER PRIMARY KEY,
    NAME VARCHAR(255) UNIQUE NOT NULL,
    CREATED_AT TIMESTAMP NOT NULL,
    LAST_UPDATED TIMESTAMP  NOT NULL,
    VERSION INTEGER NOT NULL
);
INSERT INTO USER_STATUS VALUES (1, 'ENABLED', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO USER_STATUS VALUES (2, 'DISABLED', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
CREATE SEQUENCE USER_STATUS_SEQUENCE START 3;

CREATE TABLE USER_SALUTATION (
    ID INTEGER PRIMARY KEY,
    NAME VARCHAR(255) UNIQUE NOT NULL,
    CREATED_AT TIMESTAMP NOT NULL,
    LAST_UPDATED TIMESTAMP NOT NULL,
    VERSION INTEGER NOT NULL
);
INSERT INTO USER_SALUTATION VALUES (1, 'MR', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO USER_SALUTATION VALUES (2, 'MRS', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO USER_SALUTATION VALUES (3, 'MISS', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
CREATE SEQUENCE USER_SALUTATION_SEQUENCE START 4;

CREATE TABLE _USER (
    ID INTEGER PRIMARY KEY,
    USER_NAME VARCHAR(255) UNIQUE NOT NULL,
    DISPLAY_NAME VARCHAR(255) NOT NULL,
    FIRST_NAME VARCHAR(255) NOT NULL,
    LAST_NAME VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(255) UNIQUE NOT NULL,
    USER_SALUTATION_ID INTEGER REFERENCES USER_SALUTATION(ID),
    IMAGE_SOURCE VARCHAR(255),
    PHONE_NUMBER VARCHAR(255),
    USER_STATUS_ID INTEGER REFERENCES USER_STATUS(ID),
    CREATED_AT TIMESTAMP NOT NULL,
    LAST_UPDATED TIMESTAMP  NOT NULL,
    VERSION INTEGER NOT NULL
);
CREATE INDEX IDX_USER_USER_STATUS ON _USER(USER_STATUS_ID);
CREATE INDEX IDX_USER_USER_SALUTATION ON _USER(USER_SALUTATION_ID);
CREATE SEQUENCE USER_SEQUENCE START 1;

CREATE TABLE USER_ROLE (
    ID INTEGER PRIMARY KEY,
    NAME VARCHAR(255) UNIQUE NOT NULL,
    CREATED_AT TIMESTAMP NOT NULL,
    LAST_UPDATED TIMESTAMP NOT NULL,
    VERSION INTEGER NOT NULL
);
INSERT INTO USER_ROLE VALUES (1, 'ADMIN', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
CREATE SEQUENCE USER_ROLE_SEQUENCE START 2;

CREATE TABLE USER_ROLE_BINDING (
    ID INTEGER PRIMARY KEY,
    USER_ID INTEGER REFERENCES _USER(ID) ON DELETE CASCADE NOT NULL,
    USER_ROLE_ID INTEGER REFERENCES USER_ROLE(ID) NOT NULL,
    CREATED_AT TIMESTAMP NOT NULL,
    LAST_UPDATED TIMESTAMP NOT NULL,
    VERSION INTEGER NOT NULL
);
CREATE INDEX IDX_USER_ROLE_USER ON USER_ROLE_BINDING(USER_ID);
CREATE INDEX IDX_USER_ROLE_USER_ROLE ON USER_ROLE_BINDING(USER_ROLE_ID);
CREATE SEQUENCE USER_ROLE_BINDING_SEQUENCE START 1;
