-- Add OPERATOR role
INSERT INTO USER_ROLE (ID, NAME, CREATED_AT, LAST_UPDATED, VERSION) VALUES (2, 'OPERATOR', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);

-- Advance sequence to prevent primary key conflicts for app-created roles
ALTER SEQUENCE USER_ROLE_SEQUENCE RESTART WITH 3;
