# JPA
spring.jpa.database=POSTGRESQL
spring.jpa.show-sql=true
spring.jpa.open-in-view=true

# DB encryption properties
db.encryption.algorithm=${DB_ENCRYPTION_ALGORITHM}
db.encryption.key=${DB_ENCRYPTION_KEY}