CREATE SEQUENCE integration_sequence START WITH 1 INCREMENT BY 1;
CREATE TABLE INTEGRATION (
  id BIGINT NOT NULL PRIMARY KEY DEFAULT nextval('integration_sequence'),
  name VARCHAR(255),
  type VARCHAR(50),
  provider VARCHAR(255),
  status VARCHAR(50),
  configuration TEXT,
  version INTEGER,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  last_updated TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);
