spring.config.import=optional:classpath:base-types-application.properties,\
                     optional:classpath:config-application.properties,\
                     optional:classpath:model-application.properties,\
                     optional:classpath:api-application.properties,\
                     optional:classpath:iaas-application.properties,\
                     optional:classpath:auth-application.properties,\
                     optional:classpath:auth-aws-application.properties,\
                     optional:classpath:iaas-auth-application.properties,\
                     optional:classpath:iaas-auth-aws-application.properties,\
                     optional:classpath:repo-application.properties,\
                     optional:classpath:secrets-application.properties,\
                     optional:classpath:secrets-aws-application.properties,\
                     optional:classpath:data-application.properties,\
                     optional:classpath:data-management-application.properties,\
                     optional:classpath:jdbc-application.properties,\
                     optional:classpath:object-store-file-application.properties,\
                     optional:classpath:api-application.properties,\
                     optional:classpath:crud-application.properties,\
                     optional:classpath:repo-aggregation-application.properties,\
                     optional:classpath:object-store-file-service-application.properties,\
                     optional:classpath:object-store-file-service-aws-application.properties,\
                     optional:classpath:object-store-application.properties,\
                     optional:classpath:object-store-service-application.properties,\
                     optional:classpath:tenant-application.properties,\
                     optional:classpath:tenant-auth-application.properties,\
                     optional:classpath:tenant-persistence-application.properties,\
                     optional:classpath:tenant-persistence-management-application.properties,\
                     optional:classpath:tenant-service-application.properties,\
                     optional:classpath:money-application.properties,\
                     optional:classpath:quantity-application.properties,\
                     optional:classpath:quantity-service-application.properties,\
                     optional:classpath:quantity-management-service-application.properties,\
                     optional:classpath:address-application.properties,\
                     optional:classpath:commodity-application.properties,\
                     optional:classpath:iaas-tenant-application.properties,\
                     optional:classpath:iaas-tenant-service-application.properties,\
                     optional:classpath:user-application.properties,\
                     optional:classpath:user-service-application.properties,\
                     optional:classpath:iaas-access-application.properties,\
                     optional:classpath:iaas-access-aws-application.properties,\
                     optional:classpath:iaas-access-service-application.properties,\
                     optional:classpath:iaas-tenant-aws-application.properties,\
                     optional:classpath:iaas-tenant-idp-application.properties,\
                     optional:classpath:iaas-tenant-object-store-application.properties,\
                     optional:classpath:iaas-tenant-object-store-aws-application.properties,\
                     optional:classpath:iaas-tenant-object-store-service-application.properties,\
                     optional:classpath:iaas-tenant-idp-management-service-application.properties,\
                     optional:classpath:iaas-tenant-idp-service-aws-application.properties,\
                     optional:classpath:iaas-user-application.properties,\
                     optional:classpath:iaas-user-aws-application.properties,\
                     optional:classpath:iaas-user-service-application.properties,\
                     optional:classpath:iaas-user-service-aws-application.properties,\
                     optional:classpath:object-store-aws-application.properties,\
                     optional:classpath:object-store-service-aws-application.properties,\
                     optional:classpath:ai-service-application.properties,\
                     optional:classpath:ai-application.properties,\
                     optional:classpath:integration-application.properties,\
                     optional:classpath:integration-service-application.properties,\
                     optional:classpath:communication-application.properties,\
                     optional:classpath:communication-service-application.properties,\
                     optional:classpath:communication-twilio-application.properties
spring.jpa.show-sql=true
