spring.config.import=optional:classpath:base-types-application-test.properties,\
                     optional:classpath:config-application-test.properties,\
                     optional:classpath:model-application-test.properties,\
                     optional:classpath:api-application-test.properties,\
                     optional:classpath:iaas-application-test.properties,\
                     optional:classpath:auth-application-test.properties,\
                     optional:classpath:auth-aws-application-test.properties,\
                     optional:classpath:iaas-auth-application-test.properties,\
                     optional:classpath:iaas-auth-aws-application-test.properties,\
                     optional:classpath:repo-application-test.properties,\
                     optional:classpath:secrets-application-test.properties,\
                     optional:classpath:secrets-aws-application-test.properties,\
                     optional:classpath:data-application-test.properties,\
                     optional:classpath:data-management-application-test.properties,\
                     optional:classpath:jdbc-application-test.properties,\
                     optional:classpath:object-store-file-application-test.properties,\
                     optional:classpath:api-application-test.properties,\
                     optional:classpath:crud-application-test.properties,\
                     optional:classpath:repo-aggregation-application-test.properties,\
                     optional:classpath:object-store-file-service-application-test.properties,\
                     optional:classpath:object-store-file-service-aws-application-test.properties,\
                     optional:classpath:object-store-application-test.properties,\
                     optional:classpath:object-store-service-application-test.properties,\
                     optional:classpath:tenant-application-test.properties,\
                     optional:classpath:tenant-auth-application-test.properties,\
                     optional:classpath:tenant-persistence-application-test.properties,\
                     optional:classpath:tenant-persistence-management-application-test.properties,\
                     optional:classpath:tenant-service-application-test.properties,\
                     optional:classpath:money-application-test.properties,\
                     optional:classpath:quantity-application-test.properties,\
                     optional:classpath:quantity-service-application-test.properties,\
                     optional:classpath:quantity-management-service-application-test.properties,\
                     optional:classpath:address-application-test.properties,\
                     optional:classpath:commodity-application-test.properties,\
                     optional:classpath:iaas-tenant-application-test.properties,\
                     optional:classpath:iaas-tenant-service-application-test.properties,\
                     optional:classpath:user-application-test.properties,\
                     optional:classpath:user-service-application-test.properties,\
                     optional:classpath:iaas-access-application-test.properties,\
                     optional:classpath:iaas-access-aws-application-test.properties,\
                     optional:classpath:iaas-access-service-application-test.properties,\
                     optional:classpath:iaas-tenant-aws-application-test.properties,\
                     optional:classpath:iaas-tenant-idp-application-test.properties,\
                     optional:classpath:iaas-tenant-object-store-application-test.properties,\
                     optional:classpath:iaas-tenant-object-store-aws-application-test.properties,\
                     optional:classpath:iaas-tenant-object-store-service-application-test.properties,\
                     optional:classpath:iaas-tenant-idp-management-service-application-test.properties,\
                     optional:classpath:iaas-tenant-idp-service-aws-application-test.properties,\
                     optional:classpath:iaas-user-application-test.properties,\
                     optional:classpath:iaas-user-aws-application-test.properties,\
                     optional:classpath:iaas-user-service-application-test.properties,\
                     optional:classpath:iaas-user-service-aws-application-test.properties,\
                     optional:classpath:object-store-aws-application-test.properties,\
                     optional:classpath:object-store-service-aws-application-test.properties,\
                     optional:classpath:ai-service-application-test.properties,\
                     optional:classpath:ai-application-test.properties,\
                     optional:classpath:integration-application-test.properties,\
                     optional:classpath:integration-service-application-test.properties,\
                     optional:classpath:communication-application-test.properties,\
                     optional:classpath:communication-service-application-test.properties,\
                     optional:classpath:communication-twilio-application-test.properties

# Disable Flyway for test context (Flyway does not support HSQLDB without Teams edition)
spring.flyway.enabled=false
