CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE TENANT (
    ID UUID PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL UNIQUE,
    URL VARCHAR(255) NOT NULL UNIQUE,
    IS_READY BOOLEAN DEFAULT FALSE NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    LAST_UPDATED TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);